export const routes = {
  home: '/',
  login: '/login',
  emailVerification: '/email-verify',
  users: '/users',
  createUser: '/users/create',
  overview: '/overview',
  websiteUrls: '/website-urls',
  domains: '/domains',
  createDomain: '/domains/create',
  pendingUsers: '/pending-users',
  pendingDomains: '/pending-domains',
  categories: '/categories',
  createCategory: '/categories/create',
  accountInformation: '/account-information',
  notices: '/notices',
  supports: '/supports',
  createNotice: '/notices/create',
  createSupport: '/supports/create',
  profile: '/profiles',
};
